### Este es un archivo de peticiones HTTP para probar los endpoints de un servidor Node.js que maneja libros.

###Este es una peticion HTTP para traer todos los libros
GET http://localhost:3000/books HTTP/1.1

###Este es una petición HTTP para traer un libro específico por su id, en este caso el id es 2
GET http://localhost:3000/books/2 HTTP/1.1

###Este es una petición HTTP para crear un libro nuevo, el cual se recibe en el body de la petición
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "title": "La reina Roja",
  "author": "Victoria Aveyard",
  "year": 2015,
}

###Este es una petición HTTP para actualizar un libro existente, el cual se recibe en el body de la petición y se identifica por el id en la URL
PUT http://localhost:3000/books/3 HTTP/1.1
Content-Type: application/json

{
  "year": 1999
}

###Este es una petición HTTP para eliminar un libro existente, el cual se identifica por el id en la URL
DELETE http://localhost:3000/books/3 HTTP/1.1
